CREATE TABLE IF NOT EXISTS settlement_contract_snapshot (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  source_application VARCHAR(64) NOT NULL,
  source_event_id CHAR(32) NOT NULL,
  source_contract_id VARCHAR(128) NOT NULL,
  source_contract_no VARCHAR(128) NOT NULL,
  source_contract_version INT NOT NULL,
  customer_id VARCHAR(128) NOT NULL,
  customer_name_snapshot VARCHAR(255) NOT NULL,
  project_id VARCHAR(128) NOT NULL DEFAULT '',
  project_name_snapshot VARCHAR(255) NOT NULL DEFAULT '',
  currency CHAR(3) NOT NULL,
  contract_amount DECIMAL(18,2) NOT NULL,
  financial_status VARCHAR(32) NOT NULL,
  effective_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_contract_version (tenant_id, source_application, source_contract_id, source_contract_version),
  UNIQUE KEY uq_settlement_contract_event (tenant_id, source_application, source_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_receivable_plan (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  contract_snapshot_id CHAR(32) NOT NULL,
  installment_no INT NOT NULL,
  due_date DATE NOT NULL,
  planned_amount DECIMAL(18,2) NOT NULL,
  generation_source VARCHAR(32) NOT NULL,
  confirmation_status VARCHAR(32) NOT NULL,
  confirmation_reason VARCHAR(500) NOT NULL DEFAULT '',
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_plan_installment (tenant_id, contract_snapshot_id, installment_no),
  KEY idx_settlement_plan_status_due (tenant_id, confirmation_status, due_date),
  CONSTRAINT fk_settlement_plan_contract FOREIGN KEY (contract_snapshot_id) REFERENCES settlement_contract_snapshot(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_receivable (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  receivable_no VARCHAR(64) NOT NULL,
  contract_snapshot_id CHAR(32) NOT NULL,
  receivable_plan_id CHAR(32) NULL,
  due_date DATE NOT NULL,
  original_amount DECIMAL(18,2) NOT NULL,
  invoiced_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  received_allocated_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  write_off_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  open_amount DECIMAL(18,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  recognition_status VARCHAR(32) NOT NULL,
  collection_status VARCHAR(32) NOT NULL,
  invoice_status VARCHAR(32) NOT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_receivable_no (tenant_id, receivable_no),
  UNIQUE KEY uq_settlement_receivable_plan (tenant_id, receivable_plan_id),
  KEY idx_settlement_receivable_due (tenant_id, collection_status, due_date),
  CONSTRAINT fk_settlement_receivable_contract FOREIGN KEY (contract_snapshot_id) REFERENCES settlement_contract_snapshot(id),
  CONSTRAINT fk_settlement_receivable_plan FOREIGN KEY (receivable_plan_id) REFERENCES settlement_receivable_plan(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_invoice_request (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  request_no VARCHAR(64) NOT NULL,
  contract_snapshot_id CHAR(32) NOT NULL,
  buyer_profile_snapshot JSON NOT NULL,
  invoice_type VARCHAR(32) NOT NULL,
  amount_excl_tax DECIMAL(18,2) NOT NULL,
  tax_amount DECIMAL(18,2) NOT NULL,
  amount_incl_tax DECIMAL(18,2) NOT NULL,
  status VARCHAR(32) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  submitted_by VARCHAR(128) NOT NULL,
  approved_by VARCHAR(128) NOT NULL DEFAULT '',
  rejection_reason VARCHAR(500) NOT NULL DEFAULT '',
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_invoice_request_no (tenant_id, request_no),
  UNIQUE KEY uq_settlement_invoice_request_idempotency (tenant_id, idempotency_key),
  KEY idx_settlement_invoice_request_status (tenant_id, status, created_at),
  CONSTRAINT fk_settlement_invoice_contract FOREIGN KEY (contract_snapshot_id) REFERENCES settlement_contract_snapshot(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_receipt (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  receipt_no VARCHAR(64) NOT NULL,
  customer_id VARCHAR(128) NOT NULL,
  customer_name_snapshot VARCHAR(255) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  unallocated_amount DECIMAL(18,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  receipt_date DATE NOT NULL,
  payment_method VARCHAR(32) NOT NULL,
  bank_transaction_reference VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_receipt_no (tenant_id, receipt_no),
  UNIQUE KEY uq_settlement_receipt_bank_reference (tenant_id, bank_transaction_reference),
  UNIQUE KEY uq_settlement_receipt_idempotency (tenant_id, idempotency_key),
  KEY idx_settlement_receipt_status (tenant_id, status, receipt_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_receipt_allocation (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  allocation_no VARCHAR(64) NOT NULL,
  receipt_id CHAR(32) NOT NULL,
  receivable_id CHAR(32) NOT NULL,
  allocated_amount DECIMAL(18,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  status VARCHAR(32) NOT NULL,
  match_mode VARCHAR(32) NOT NULL,
  confirmed_by VARCHAR(128) NOT NULL,
  confirmed_at DATETIME(3) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_allocation_no (tenant_id, allocation_no),
  UNIQUE KEY uq_settlement_allocation_idempotency (tenant_id, idempotency_key),
  KEY idx_settlement_allocation_receipt (tenant_id, receipt_id),
  KEY idx_settlement_allocation_receivable (tenant_id, receivable_id),
  CONSTRAINT fk_settlement_allocation_receipt FOREIGN KEY (receipt_id) REFERENCES settlement_receipt(id),
  CONSTRAINT fk_settlement_allocation_receivable FOREIGN KEY (receivable_id) REFERENCES settlement_receivable(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_receipt_allocation_reversal (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  reversal_no VARCHAR(64) NOT NULL,
  original_allocation_id CHAR(32) NOT NULL,
  reversed_amount DECIMAL(18,2) NOT NULL,
  reason_code VARCHAR(64) NOT NULL,
  reason_detail VARCHAR(500) NOT NULL,
  approved_by VARCHAR(128) NOT NULL,
  reversed_at DATETIME(3) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_reversal_no (tenant_id, reversal_no),
  UNIQUE KEY uq_settlement_reversal_idempotency (tenant_id, idempotency_key),
  CONSTRAINT fk_settlement_reversal_allocation FOREIGN KEY (original_allocation_id) REFERENCES settlement_receipt_allocation(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_inbox_event (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  source_application VARCHAR(64) NOT NULL,
  event_id CHAR(32) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  aggregate_id VARCHAR(128) NOT NULL,
  aggregate_version INT NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  received_at DATETIME(3) NOT NULL,
  processed_at DATETIME(3) NULL,
  failure_summary VARCHAR(500) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_inbox_event (tenant_id, source_application, event_id),
  KEY idx_settlement_inbox_status (status, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_outbox_event (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  event_id CHAR(32) NOT NULL,
  destination VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(128) NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  available_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  delivered_at DATETIME(3) NULL,
  last_error_summary VARCHAR(500) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_outbox_event (tenant_id, event_id),
  KEY idx_settlement_outbox_ready (status, available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
