CREATE TABLE IF NOT EXISTS settlement_credit_sync (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  event_id CHAR(32) NOT NULL,
  allocation_id CHAR(32) NOT NULL,
  receivable_id CHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  payload_json JSON NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  locked_at DATETIME(3) NULL,
  last_attempt_at DATETIME(3) NULL,
  delivered_at DATETIME(3) NULL,
  last_error_summary VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settlement_credit_sync_event (tenant_id,event_id),
  UNIQUE KEY uq_settlement_credit_sync_receivable (tenant_id,receivable_id),
  UNIQUE KEY uq_settlement_credit_sync_allocation (tenant_id,allocation_id),
  KEY idx_settlement_credit_sync_retry (tenant_id,status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
